# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PROJECTS/IdentVals/IdentVals.ui'
#
# Created: Sat Mar 14 09:27:02 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(800, 480)
        Dialog.setMaximumSize(QtCore.QSize(800, 480))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 10, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(110, 151, 579, 62))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnP8_26 = QtGui.QCommandLinkButton(self.widget)
        self.btnP8_26.setEnabled(True)
        self.btnP8_26.setMouseTracking(False)
        self.btnP8_26.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("buttons/Off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("buttons/On.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnP8_26.setIcon(icon)
        self.btnP8_26.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_26.setShortcut(_fromUtf8(""))
        self.btnP8_26.setCheckable(True)
        self.btnP8_26.setChecked(False)
        self.btnP8_26.setAutoRepeat(False)
        self.btnP8_26.setAutoExclusive(False)
        self.btnP8_26.setAutoDefault(False)
        self.btnP8_26.setObjectName(_fromUtf8("btnP8_26"))
        self.horizontalLayout.addWidget(self.btnP8_26)
        self.btnP8_18 = QtGui.QCommandLinkButton(self.widget)
        self.btnP8_18.setEnabled(True)
        self.btnP8_18.setMouseTracking(False)
        self.btnP8_18.setText(_fromUtf8(""))
        self.btnP8_18.setIcon(icon)
        self.btnP8_18.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_18.setShortcut(_fromUtf8(""))
        self.btnP8_18.setCheckable(True)
        self.btnP8_18.setChecked(False)
        self.btnP8_18.setAutoRepeat(False)
        self.btnP8_18.setAutoExclusive(False)
        self.btnP8_18.setAutoDefault(False)
        self.btnP8_18.setObjectName(_fromUtf8("btnP8_18"))
        self.horizontalLayout.addWidget(self.btnP8_18)
        self.btnP8_17 = QtGui.QCommandLinkButton(self.widget)
        self.btnP8_17.setEnabled(True)
        self.btnP8_17.setMouseTracking(False)
        self.btnP8_17.setText(_fromUtf8(""))
        self.btnP8_17.setIcon(icon)
        self.btnP8_17.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_17.setShortcut(_fromUtf8(""))
        self.btnP8_17.setCheckable(True)
        self.btnP8_17.setChecked(False)
        self.btnP8_17.setAutoRepeat(False)
        self.btnP8_17.setAutoExclusive(False)
        self.btnP8_17.setAutoDefault(False)
        self.btnP8_17.setObjectName(_fromUtf8("btnP8_17"))
        self.horizontalLayout.addWidget(self.btnP8_17)
        self.btnP8_16 = QtGui.QCommandLinkButton(self.widget)
        self.btnP8_16.setEnabled(True)
        self.btnP8_16.setMouseTracking(False)
        self.btnP8_16.setText(_fromUtf8(""))
        self.btnP8_16.setIcon(icon)
        self.btnP8_16.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_16.setShortcut(_fromUtf8(""))
        self.btnP8_16.setCheckable(True)
        self.btnP8_16.setChecked(False)
        self.btnP8_16.setAutoRepeat(False)
        self.btnP8_16.setAutoExclusive(False)
        self.btnP8_16.setAutoDefault(False)
        self.btnP8_16.setObjectName(_fromUtf8("btnP8_16"))
        self.horizontalLayout.addWidget(self.btnP8_16)
        self.btnP8_15 = QtGui.QCommandLinkButton(self.widget)
        self.btnP8_15.setEnabled(True)
        self.btnP8_15.setMouseTracking(False)
        self.btnP8_15.setText(_fromUtf8(""))
        self.btnP8_15.setIcon(icon)
        self.btnP8_15.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_15.setShortcut(_fromUtf8(""))
        self.btnP8_15.setCheckable(True)
        self.btnP8_15.setChecked(False)
        self.btnP8_15.setAutoRepeat(False)
        self.btnP8_15.setAutoExclusive(True)
        self.btnP8_15.setAutoDefault(False)
        self.btnP8_15.setObjectName(_fromUtf8("btnP8_15"))
        self.horizontalLayout.addWidget(self.btnP8_15)
        self.widget1 = QtGui.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(110, 301, 579, 62))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnP8_14 = QtGui.QCommandLinkButton(self.widget1)
        self.btnP8_14.setEnabled(True)
        self.btnP8_14.setMouseTracking(False)
        self.btnP8_14.setText(_fromUtf8(""))
        self.btnP8_14.setIcon(icon)
        self.btnP8_14.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_14.setShortcut(_fromUtf8(""))
        self.btnP8_14.setCheckable(True)
        self.btnP8_14.setChecked(False)
        self.btnP8_14.setAutoRepeat(False)
        self.btnP8_14.setAutoExclusive(False)
        self.btnP8_14.setAutoDefault(False)
        self.btnP8_14.setObjectName(_fromUtf8("btnP8_14"))
        self.horizontalLayout_2.addWidget(self.btnP8_14)
        self.btnP8_12 = QtGui.QCommandLinkButton(self.widget1)
        self.btnP8_12.setEnabled(True)
        self.btnP8_12.setMouseTracking(False)
        self.btnP8_12.setText(_fromUtf8(""))
        self.btnP8_12.setIcon(icon)
        self.btnP8_12.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_12.setShortcut(_fromUtf8(""))
        self.btnP8_12.setCheckable(True)
        self.btnP8_12.setChecked(False)
        self.btnP8_12.setAutoRepeat(False)
        self.btnP8_12.setAutoExclusive(False)
        self.btnP8_12.setAutoDefault(False)
        self.btnP8_12.setObjectName(_fromUtf8("btnP8_12"))
        self.horizontalLayout_2.addWidget(self.btnP8_12)
        self.btnP8_11 = QtGui.QCommandLinkButton(self.widget1)
        self.btnP8_11.setEnabled(True)
        self.btnP8_11.setMouseTracking(False)
        self.btnP8_11.setText(_fromUtf8(""))
        self.btnP8_11.setIcon(icon)
        self.btnP8_11.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_11.setShortcut(_fromUtf8(""))
        self.btnP8_11.setCheckable(True)
        self.btnP8_11.setChecked(False)
        self.btnP8_11.setAutoRepeat(False)
        self.btnP8_11.setAutoExclusive(False)
        self.btnP8_11.setAutoDefault(False)
        self.btnP8_11.setObjectName(_fromUtf8("btnP8_11"))
        self.horizontalLayout_2.addWidget(self.btnP8_11)
        self.btnP8_10 = QtGui.QCommandLinkButton(self.widget1)
        self.btnP8_10.setEnabled(True)
        self.btnP8_10.setMouseTracking(False)
        self.btnP8_10.setText(_fromUtf8(""))
        self.btnP8_10.setIcon(icon)
        self.btnP8_10.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_10.setShortcut(_fromUtf8(""))
        self.btnP8_10.setCheckable(True)
        self.btnP8_10.setChecked(False)
        self.btnP8_10.setAutoRepeat(False)
        self.btnP8_10.setAutoExclusive(False)
        self.btnP8_10.setAutoDefault(False)
        self.btnP8_10.setObjectName(_fromUtf8("btnP8_10"))
        self.horizontalLayout_2.addWidget(self.btnP8_10)
        self.btnP8_9 = QtGui.QCommandLinkButton(self.widget1)
        self.btnP8_9.setEnabled(True)
        self.btnP8_9.setMouseTracking(False)
        self.btnP8_9.setText(_fromUtf8(""))
        self.btnP8_9.setIcon(icon)
        self.btnP8_9.setIconSize(QtCore.QSize(40, 40))
        self.btnP8_9.setShortcut(_fromUtf8(""))
        self.btnP8_9.setCheckable(True)
        self.btnP8_9.setChecked(False)
        self.btnP8_9.setAutoRepeat(False)
        self.btnP8_9.setAutoExclusive(True)
        self.btnP8_9.setAutoDefault(False)
        self.btnP8_9.setObjectName(_fromUtf8("btnP8_9"))
        self.horizontalLayout_2.addWidget(self.btnP8_9)
        self.widget2 = QtGui.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(110, 120, 581, 25))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.widget3 = QtGui.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(110, 270, 581, 25))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Identificacion de Valvulas", None))
        self.label_4.setText(_translate("Dialog", "P8_17", None))
        self.label_3.setText(_translate("Dialog", "P8_18", None))
        self.label_5.setText(_translate("Dialog", "P8_16", None))
        self.label_6.setText(_translate("Dialog", "P8_15", None))
        self.label_2.setText(_translate("Dialog", "P8_26", None))
        self.label_8.setText(_translate("Dialog", "P8_12", None))
        self.label_10.setText(_translate("Dialog", "P8_10", None))
        self.label_9.setText(_translate("Dialog", "P8_11", None))
        self.label_7.setText(_translate("Dialog", "P8_14", None))
        self.label_11.setText(_translate("Dialog", "P8_9", None))

